import axios from "axios";
import useSWR from "swr";
// Generated by https://quicktype.io

export interface Succes {
  succes: Succe[];
}

export interface Succe {
  id:         number;
  nombre:     string;
  apellido:   string;
  email:      string;
  telefono:   string;
  mensaje:    string;
  created_at: Date;
  updated_at: Date;
}

export const PanelContactenos = () => {
  const url = import.meta.env.VITE_API_URL;

  const {data,isLoading} = useSWR(`${url}/idexcontactos`,()=>
  axios.get(`${url}/idexcontactos`))
  if(isLoading)
    {
      return (
        <p className="text-3xl text-green-500 font-bold animate-bounce">Cargando Contactos...</p>
      )
    }
  const listacontactos:Succes = data?.data
  return (
    <section className="w-full h-full flex flex-col gap-5 p-2">
      <h1 className="text-3xl font-bold text-slate-300 text-center">
        Contactos
      </h1>
      <table>
        <thead>
          <tr className="w-full text-white text-center bg-sky-800">
            <td>Fecha de contacto</td>
            <td>Nombre</td>
            <td>Apellido</td>
            <td>Telefono</td>
            <td>Email</td>
            <td>Mensaje</td>
          </tr>
        </thead>
        <tbody>
          {listacontactos?.succes?.map(contacto=>(
            <tr className="text-slate-300  text-center hover:bg-sky-500">
              <td>{contacto.created_at.toString()}</td>
              <td>{contacto.nombre}</td>
              <td>{contacto.apellido}</td>
              <td>{contacto.telefono}</td>
              <td>{contacto.email}</td>
              <td>
                {contacto.mensaje}                
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
};
