import axios, { isAxiosError } from "axios";
import React, { ChangeEvent, useState } from "react";
// Generated by https://quicktype.io

export interface Errors {
  message: string;
  errors:  ErrorsClass;
}

export interface ErrorsClass {
  titulo:  string[];
  imagen:  string[];
  noticia: string[];
}
// Generated by https://quicktype.io

export interface Respuesta {
  succes: string;
}

export const PanelNoticias = () => {
  const url = import.meta.env.VITE_API_URL;
  const token = localStorage.getItem("token");
  const [respuesta,setRespuesta] = useState<Respuesta | null>()
  const [error,setError] = useState<Errors | null>()
  const [loading,setloading] = useState<boolean>(false)
  const [titulo,setTitulo] = useState<string>('');
  const [imagen,setImagen] = useState<File | undefined >();
  const [noticia,setNoticia] = useState<string>('');
  const almacenadoImagen = async(e:ChangeEvent<HTMLInputElement>) =>
    {
      if (e.target.files && e.target.files.length > 0) {
        setImagen(e.target.files[0]);
      }
      console.log(imagen)
    }
  const crearNoticia:React.FormEventHandler<HTMLFormElement> = async (e) =>{
    e.preventDefault();
    const datos = {
      titulo,
      imagen:imagen,
      noticia
    }
    setloading(true)
    setError(null)
    setRespuesta(null)
    try {
        const {data} = await axios.post(`${url}/createnoticia`,datos,{
          headers:{
            Authorization:`Bearer ${token}`,
            "Content-Type": "multipart/form-data",
          }
        })
        setRespuesta(data)
    } catch (error) {
      if(isAxiosError(error) && error.response ){
        setError(error.response.data);
      }
    }
    setloading(false)


  }

  // console.log(respuesta)
  // console.log(error)
  return (
    <section className="w-full h-auto flex flex-col gap-5 p-2 overflow-auto">
      <h1 className="text-3xl fotn-bold text-slate-300 text-center">
        Creacion de noticias
      </h1>
      <p className={`${loading ? 'text-green-500 text-sm animate-bounce' : 'hidden'}`}>Cargando datos al servidor</p>
      <p className={`${respuesta?.succes ? 'text-green-500 text-sm ' : 'hidden'}`}>{respuesta?.succes}</p>
      
      <div className="w-full  flex flex-row gap-2 ">
        {/* formulario */}
        <form
          action=""
          onSubmit={crearNoticia}
          className="w-1/3 h-full flex flex-col gap-5 text-slate-300 p-2"
        >
          <label htmlFor="">Titulo</label>
          <input type="text" onChange={(e)=>setTitulo(e.target.value)}  value={titulo} className="border rounded-xl bg-[#1D2432] p-2" />
          <p className={`${error?.errors?.titulo ? 'text-red-500 text-sm' : 'hidden'}`}>{error?.errors?.titulo}</p>
          <label htmlFor="">Imagen</label>
          <input type="file" onChange={almacenadoImagen}  />
          <p className={`${error?.errors?.imagen ? 'text-red-500 text-sm' : 'hidden'}`}>{error?.errors?.imagen}</p>

          <label htmlFor="">Noticia</label>
          <textarea
            onChange={(e)=>setNoticia(e.target.value)}
            value={noticia}
            className="border rounded-xl bg-[#1D2432] p-2"
          ></textarea>
          <p className={`${error?.errors?.noticia ? 'text-red-500 text-sm' : 'hidden'}`}>{error?.errors?.noticia}</p>

          <input
            type="submit"
            className="border p-2 bg-green-500 text-white font-bold cursor-pointer hover:opacity-70 transition-all"
          />
        </form>
        {/* lista de noticias */}
        <div className="w-full  overflow-auto">
          <table className="w-full text-center">
            <thead>
              <tr className=" w-full bg-sky-800 text-white ">
                <td>Fecha</td>
                <td>Titulo</td>
                <td>Imagen</td>
                <td>Noticia</td>
                <td>Acciones</td>
              </tr>
            </thead>
            <tbody>
              <tr className="text-white text-center border-b">
                <td>01/01/24</td>
                <td>Primera noticia</td>
                <td>imagen</td>
                <td className="w-96 h-auto">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla
                  illum odio similique sint corporis. Deserunt explicabo, quod
                  laboriosam neque sunt odio at dolores voluptate perferendis
                  blanditiis molestias distinctio animi voluptatem!
                </td>
                <td className="">
                  <button className="p-2 text-white font-bold hover:opacity-70 transition-all bg-sky-500 m-2">
                    Editar
                  </button>
                  <button className="p-2 text-white font-bold hover:opacity-70 transition-all bg-red-500 m-2">
                    Eliminar
                  </button>
                </td>
              </tr>
              <tr className="text-white text-center border-b">
                <td>01/01/24</td>
                <td>Primera noticia</td>
                <td>imagen</td>
                <td className="w-96 h-auto">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla
                  illum odio similique sint corporis. Deserunt explicabo, quod
                  laboriosam neque sunt odio at dolores voluptate perferendis
                  blanditiis molestias distinctio animi voluptatem!
                </td>
                <td className="">
                  <button className="p-2 text-white font-bold hover:opacity-70 transition-all bg-sky-500 m-2">
                    Editar
                  </button>
                  <button className="p-2 text-white font-bold hover:opacity-70 transition-all bg-red-500 m-2">
                    Eliminar
                  </button>
                </td>
              </tr>
              <tr className="text-white text-center border-b">
                <td>01/01/24</td>
                <td>Primera noticia</td>
                <td>imagen</td>
                <td className="w-96 h-auto">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla
                  illum odio similique sint corporis. Deserunt explicabo, quod
                  laboriosam neque sunt odio at dolores voluptate perferendis
                  blanditiis molestias distinctio animi voluptatem!
                </td>
                <td className="">
                  <button className="p-2 text-white font-bold hover:opacity-70 transition-all bg-sky-500 m-2">
                    Editar
                  </button>
                  <button className="p-2 text-white font-bold hover:opacity-70 transition-all bg-red-500 m-2">
                    Eliminar
                  </button>
                </td>
              </tr>
              <tr className="text-white text-center border-b">
                <td>01/01/24</td>
                <td>Primera noticia</td>
                <td>imagen</td>
                <td className="w-96 h-auto">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla
                  illum odio similique sint corporis. Deserunt explicabo, quod
                  laboriosam neque sunt odio at dolores voluptate perferendis
                  blanditiis molestias distinctio animi voluptatem!
                </td>
                <td className="">
                  <button className="p-2 text-white font-bold hover:opacity-70 transition-all bg-sky-500 m-2">
                    Editar
                  </button>
                  <button className="p-2 text-white font-bold hover:opacity-70 transition-all bg-red-500 m-2">
                    Eliminar
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
};
